openapi: 3.1.0
info:
  title: Google Calendar Event Search API
  version: 1.0.0
  description: An API endpoint to search Google Calendar events by summary and time range.
servers:
  - url: https://b0es2hb9q7.execute-api.us-east-1.amazonaws.com/default
    description: API Gateway endpoint for Lambda
paths:
  /calendar-search-events-agent-action:
    get:
      operationId: searchGoogleCalendarEvent
      summary: Search Google Calendar Events
      description: Search for events in Google Calendar by summary, startDateTime, and endDateTime.
      parameters:
        - in: query
          name: summary
          schema:
            type: string
          required: true
          description: The keyword to search for in event summaries.
        - in: query
          name: startDateTime
          schema:
            type: string
            format: date-time
          required: true
          description: The start of the time range to search (ISO 8601 format).
        - in: query
          name: endDateTime
          schema:
            type: string
            format: date-time
          required: true
          description: The end of the time range to search (ISO 8601 format).
      responses:
        '200':
          description: A list of matching events.
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The ID of the event.
                        summary:
                          type: string
                          description: The summary or title of the event.
                        start:
                          type: string
                          format: date-time
                          description: The start time of the event.
                        end:
                          type: string
                          format: date-time
                          description: The end time of the event.
        '400':
          description: Invalid request (e.g., missing parameters or invalid format).
        '500':
          description: Server error or Google Calendar API error.
