openapi: 3.1.0
info:
  title: Event Attributes Schema
  description: OpenAPI schema for mapping event attributes.
  version: 1.0.0
servers:
  - url: https://b0es2hb9q7.execute-api.us-east-1.amazonaws.com/default
    description: API Gateway endpoint for Lambda
paths:
  /calendar-create-event-agent-action:
    post:
      operationId: createGoogleCalendarEvent
      summary: Create an event
      description: Endpoint to create an event with specific attributes.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                summary:
                  type: string
                  description: A brief summary of the event.
                  example: Team Meeting
                description:
                  type: string
                  description: A detailed description of the event.
                  example: Discuss quarterly goals and progress.
                location:
                  type: string
                  description: The location of the event.
                  example: Conference Room A
                attendees:
                  type: string
                  description: A comma-separated list of attendees' emails.
                  example: john.doe@example.com, jane.doe@example.com
                startDateTime:
                  type: string
                  format: date-time
                  description: The start date and time of the event in ISO 8601 format.
                  example: 2024-12-30T10:00:00Z
                endDateTime:
                  type: string
                  format: date-time
                  description: The end date and time of the event in ISO 8601 format.
                  example: 2024-12-30T11:00:00Z
      responses:
        '201':
          description: Event created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The unique identifier of the created event.
                    example: 12345